name: C CI - Build Status on Linux

on:
  push:
    branches: [Production]
  pull_request:
    branches: [Production]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make -C 3_Implementation/ all
      - name: Export Release Timestamp
        run: echo "APP_VERSION=release_$(date +'%Y-%m-%d_%H-%m-%S')" >> $GITHUB_ENV
      - name: Release Apps on windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_F1 }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 3_Implementation/Build/*.out
          # asset_name: azblogfilter.windows-amd64.zip
          # asset_content_type: application/zip
