name: CodeQuality Dynamic Code Analysis Valgrind
on:
  push:
    branches: [Production]
  pull_request:
    branches: [Production]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: apt install dependency
        run: |
          sudo apt-get -y install valgrind
          sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev
      # - name: make test
      #   run: make -C 3_Implement/ test
      - name: Valgrind
        run: valgrind ./3_Implementation/Build/F1-Pitstop-Strategy-Generator.out
