name: Unit Testing - Unity

on:
  push:
    branches: [Production]
  pull_request:
    branches: [Productions]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make -C 3_Implementation/ test
