name: Unit Testing - Unity

on:
  push:
    branches: [Production]
  pull_request:
    branches: [Production]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: testing
        run: make -C 3_Implementation/ testing
